---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - group_vars/all

  tasks:
  - ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     keypair="{{ ec2_keypair }}"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'ansible_group':'{{ ec2_tag_cassandra }}', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_cassandra_''{{ tower_user_name }}'}"
     count="{{ ec2_instance_count}}"
     wait=true
    register: ec2
